### ISSUE TITLE
Filer.find

### ISSUE THREAD

**Issue by mudcube** [ebidel/filer.js#52]
What do you think of a find command?
```
Filer.find(params, successCallback, opt_errorHandler);
```
Where params could be an object, or a string. 

If a string was supplied it would be a regexp representation of a filename. 

Whereas if an object was supplied there would be various options such:
* "exclude" - regexp operator to exclude matches
* "isDirectory" - only returns directories
* "isFile" - only returns files
* "depth" - depth to search to
* "time" - an object representing the normal unix time based searches

**Comment by ebidel** [comment]
I'm not actively implementing new features as the Filesystem API is chrome-only and no other browser vendors are going to implement it.
