### ISSUE TITLE
how can i continual read realtime mp3 buffer to the temporary MP3 file?Can anyone help?Thanks!!

### ISSUE THREAD

**Issue by aizhilong** [ebidel/filer.js#53]
I use node.js an server and get mp3 buffer from android client.The i need to play the mp3 buffer reatime across the browser,so i want to put the mp3 buffer to a temporary MP3 file and play it. How can i do?

**Comment by darkyen** [comment]
this is not the right place to ask imo,

you should ask this on stackoverflow.com

**Comment by ebidel** [comment]
Agreed :)
