### ISSUE TITLE
Where on my disk can I find file I have created?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [ebidel/filer.js#59]
So, I created script like this.

```
var filer = new Filer();
filer.init({persistent: true}, function (fs) {
    console.log('success');
    test();
}, onError);
function test() {
    // create new file
    filer.create('myFile.txt', false, function(fileEntry) {

    }, onError);
}
```
after listing files under root I see my "myFile.txt"

  ```
filer.ls('..', function (entries) {
        console.log(entries);
    }, onError);
```
But where can I find it physically?
  
http://stackoverflow.com/questions/37940927/where-can-i-find-file-i-created-with-javascript-file-api-using-filer-js

**Comment by ebidel** [comment]
The short answer is that you really can't. IIRC, you used to be able to drill into Chrome's Application folder and find these files under resources. But it's non-obvious where they are. Furthermore, the actual file names are obfuscated by the browser.

**Comment by dmitrykolesnikovich** [comment]
How can I read *.txt file from my *.js file if this text file located a the same root as script does? Is it possile?

**Comment by ebidel** [comment]
Check out http://www.html5rocks.com/en/tutorials/file/filesystem/
