### ISSUE TITLE
compatibility with Cordova File Plugin

### ISSUE THREAD

**Issue by giorgiobeggiora** [ebidel/filer.js#65]
please make this script compatible with https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/

Cordova developers really need it!

Thanks

**Comment by ebidel** [comment]
The Filesystem API in Chromium is not an API other browsers plan to adopt. As a result, I'm not actively adding features to filer.js.

That said, you're welcome create a fork, modify it, and create something that works with Cordova.

Cheers.
